Add support for mailbox commands with command line arguments

diff --git a/checkmail b/checkmail
--- a/checkmail
+++ b/checkmail
@@ -3,12 +3,11 @@
 set -euo pipefail
 
 MAIL_D="/var/mail/${LOGNAME}"
-MAIL_COMMAND="${1:-}"
 
 export PAGER=${CHECKMAIL_PAGER:-${PAGER:-more}}
 
 usage_exit() {
-	echo "Usage: $0 [<mailbox_command>]"
+	echo "Usage: $0 [<mailbox_command> [<arguments...>]]"
 	exit "${1:-0}"
 }
 
@@ -28,22 +27,23 @@ get_mailbox_name() {
 }
 
 [[ "${1:-}" = "--help" ]] && usage_exit 0
-[[ $# -gt 1 ]] && usage_exit 2 >&2
+
+mailbox_command=("$@")
 
 if [[ ! -d "${MAIL_D}/cur" ]]; then
 	echo "Maildir \"${MAIL_D}\" not found!" >&2
 	exit 1
 fi
 
-if [[ -z "${MAIL_COMMAND}" ]]; then
+if [[ -z "${mailbox_command[0]:-}" ]]; then
 	if command -v s-nail >/dev/null 2>&1; then
-		MAIL_COMMAND="s-nail"
+		mailbox_command=("s-nail")
 	else
-		MAIL_COMMAND="mail"
+		mailbox_command=("mail")
 	fi
 fi
-if ! command -v "${MAIL_COMMAND}" >/dev/null 2>&1; then
-	echo "Command not found: \"${MAIL_COMMAND}\"!"
+if ! command -v "${mailbox_command[0]}" >/dev/null 2>&1; then
+	echo "Command not found: \"${mailbox_command[0]}\"!"
 	exit 1
 fi
 
@@ -64,9 +64,9 @@ done
 declare -i exit_code=0
 for mailbox in "${mailboxes[@]}"; do
 	printf '\nOpening "\e[1m%s\e[0m" with %s:\n' \
-		"$(get_mailbox_name "$mailbox")" "${MAIL_COMMAND}"
+		"$(get_mailbox_name "$mailbox")" "${mailbox_command[0]}"
 	invocations=$((invocations + 1))
-	"${MAIL_COMMAND}" -f "${mailbox}" && exit_code=0 || exit_code=$?
+	"${mailbox_command[@]}" -f "${mailbox}" && exit_code=0 || exit_code=$?
 	[[ $exit_code -eq 0 ]] || break
 done
 echo
@@ -77,8 +77,9 @@ else
 	total_info=""
 fi
 if [[ $invocations -eq 1 ]]; then
-	echo "One mailbox${total_info} with new mail shown."
+	mailbox_info="one mailbox"
 else
-	echo "$invocations mailboxes${total_info} with new mail shown."
+	mailbox_info="$invocations mailboxes"
 fi
+echo "Called \"${mailbox_command[0]}\" on ${mailbox_info}${total_info} with unread mail."
 exit $exit_code
